#!/usr/bin/env python3
"""Create deterministic systemd instance topology from mission.yaml."""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from purdue_rov_cv.config.loader import load_config

_GENERATED_HEADER = "# Generated by scripts/configure_deployment.py\n"
_MANAGED_LINK_TARGETS = {
    "purdue-cv-camera@": "../purdue-cv-camera@.service",
    "purdue-cv-module@": "../purdue-cv-module@.service",
    "purdue-cv-video-receiver@": "../purdue-cv-video-receiver@.service",
    "purdue-cv-recorder.service": "../purdue-cv-recorder.service",
}


def _link(directory: Path, name: str, target: str) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / name
    if path.is_symlink() and os.readlink(path) == target:
        return
    if path.exists() or path.is_symlink():
        raise RuntimeError(f"refusing to replace unmanaged systemd link: {path}")
    path.symlink_to(target)


def _managed_target(name: str) -> str | None:
    for prefix, target in _MANAGED_LINK_TARGETS.items():
        if name == prefix or (prefix.endswith("@") and name.startswith(prefix) and name.endswith(".service")):
            return target
    return None


def _remove_stale_links(wants: Path, expected: set[str], changed: list[Path]) -> None:
    if not wants.exists():
        return
    for path in wants.iterdir():
        target = _managed_target(path.name)
        if path.name in expected or target is None or not path.is_symlink():
            continue
        if os.readlink(path) != target:
            continue
        path.unlink()
        changed.append(path)


def _remove_stale_drop_ins(unit_root: Path, expected_modules: set[str], changed: list[Path]) -> None:
    for directory in unit_root.glob("purdue-cv-module@*.service.d"):
        module_name = directory.name.removeprefix("purdue-cv-module@").removesuffix(".service.d")
        path = directory / "10-camera-readiness.conf"
        if module_name in expected_modules or not path.is_file():
            continue
        try:
            managed = path.read_text(encoding="utf-8").startswith(_GENERATED_HEADER)
        except OSError:
            managed = False
        if not managed:
            continue
        path.unlink()
        changed.append(path)
        try:
            directory.rmdir()
        except OSError:
            pass


def configure(config_path: Path, unit_root: Path, role: str) -> tuple[Path, ...]:
    config = load_config(config_path, environ={})
    changed: list[Path] = []
    target = "purdue-cv-onboard.target" if role == "pi" else "purdue-cv-surface.target"
    wants = unit_root / f"{target}.wants"
    if role == "pi":
        expected_modules = {task_id for task_id, task in config.tasks.items() if task.enabled}
        expected = {
            *{f"purdue-cv-camera@{camera_id}.service" for camera_id in config.cameras},
            *{f"purdue-cv-module@{task_id}.service" for task_id in expected_modules},
        }
        _remove_stale_links(wants, expected, changed)
        _remove_stale_drop_ins(unit_root, expected_modules, changed)
        for camera_id in sorted(config.cameras):
            name = f"purdue-cv-camera@{camera_id}.service"
            path = wants / name
            _link(wants, name, "../purdue-cv-camera@.service")
            changed.append(path)
        for task_id, task in sorted(config.tasks.items()):
            if not task.enabled:
                continue
            name = f"purdue-cv-module@{task_id}.service"
            path = wants / name
            _link(wants, name, "../purdue-cv-module@.service")
            changed.append(path)
            drop_in = unit_root / f"{name}.d" / "10-camera-readiness.conf"
            content = (
                _GENERATED_HEADER + "[Unit]\n"
                f"After=purdue-cv-camera@{task.input_camera}.service\n"
                f"Requires=purdue-cv-camera@{task.input_camera}.service\n"
            )
            drop_in.parent.mkdir(parents=True, exist_ok=True)
            if drop_in.exists() and drop_in.read_text(encoding="utf-8") != content:
                raise RuntimeError(f"refusing to replace modified managed drop-in: {drop_in}")
            drop_in.write_text(content, encoding="utf-8")
            changed.append(drop_in)
    else:
        expected = {
            f"purdue-cv-video-receiver@{camera_id}.service"
            for camera_id, camera in config.cameras.items()
            if camera.stream_to_surface
        }
        if config.recording.enabled:
            expected.add("purdue-cv-recorder.service")
        _remove_stale_links(wants, expected, changed)
        for camera_id, camera in sorted(config.cameras.items()):
            if not camera.stream_to_surface:
                continue
            name = f"purdue-cv-video-receiver@{camera_id}.service"
            path = wants / name
            _link(wants, name, "../purdue-cv-video-receiver@.service")
            changed.append(path)
        if config.recording.enabled:
            path = wants / "purdue-cv-recorder.service"
            _link(wants, path.name, "../purdue-cv-recorder.service")
            changed.append(path)
    return tuple(changed)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--unit-root", type=Path, default=Path("/etc/systemd/system"))
    parser.add_argument("--role", choices=("pi", "surface"), required=True)
    args = parser.parse_args()
    for path in configure(args.config, args.unit_root, args.role):
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
